In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
url = "https://raw.githubusercontent.com/Ezeysay16/veridosyalari/main/Fifa_world_cup_matches.csv"
data = pd.read_csv(url)
data.head()

,team1,team2,possession team1,possession team2,possession in contest,number of goals team1,number of goals team2,date,hour,category,...,penalties scored team1,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2
0,QATAR,ECUADOR,42%,50%,8%,0,2,20 NOV 2022,17 : 00,Group A,...,0,1,6,5,0,0,52,72,256,279
1,ENGLAND,IRAN,72%,19%,9%,6,2,21 NOV 2022,14 : 00,Group B,...,0,1,8,13,0,0,63,72,139,416
2,SENEGAL,NETHERLANDS,44%,45%,11%,0,2,21 NOV 2022,17 : 00,Group A,...,0,0,9,15,0,0,63,73,263,251
3,UNITED STATES,WALES,51%,39%,10%,1,1,21 NOV 2022,20 : 00,Group B,...,0,1,7,7,0,0,81,72,242,292
4,ARGENTINA,SAUDI ARABIA,64%,24%,12%,1,2,22 NOV 2022,11 : 00,Group C,...,1,0,4,14,0,0,65,80,163,361

**Soru 1**

*The worst game in the world cup is the one where a team
  dominates too much the other teams (i.e posession ratio is the highest)
  Implement this function such that it finds the highest ratio between 
  'possession team1' and 'possession team2' (and its inverse) to find the worst 
  game and returns the following info for that game:
    team1, team2, date, possession team1 and possession team2*

In [4]:
data["possession team1"] = data["possession team1"].str.rstrip("%").astype(int)
data["possession team2"] = data["possession team2"].str.rstrip("%").astype(int)
data["dif"] = abs(data["possession team1"] - data["possession team2"])

In [5]:

data.loc[data["dif"].argmax()]

team1                                JAPAN
team2                                SPAIN
possession team1                        14
possession team2                        78
possession in contest                   8%
                                     ...
forced turnovers team1                  85
forced turnovers team2                  49
defensive pressures applied team1      637
defensive pressures applied team2      150
dif                                     64
Name: 42, Length: 89, dtype: object

In [6]:
team1 = data.loc[data["dif"].argmax(), "team1"]
team2 = data.loc[data["dif"].argmax(), "team2"]
date = data.loc[data["dif"].argmax(), "date"]
pos1 = data.loc[data["dif"].argmax(), "possession team1"]
pos2 = data.loc[data["dif"].argmax(), "possession team2"]

In [7]:
print(team1, 'vs',team2, date, 'possession team1:', pos1, 'possession team2:', pos2)

JAPAN vs SPAIN 01 DEC 2022 possession team1: 14 possession team2: 78

**Soru 2**

*Efficiency of a team is defined by the number of goals divided by possession.
  Implement this function such that it returns the name of the most efficient 
  team and the value for efficiency (number of goals by possesion). Take into
  account that a team may appear as team1 or team2 in a game.*

In [8]:
data.head()

,team1,team2,possession team1,possession team2,possession in contest,number of goals team1,number of goals team2,date,hour,category,...,penalties scored team2,goal preventions team1,goal preventions team2,own goals team1,own goals team2,forced turnovers team1,forced turnovers team2,defensive pressures applied team1,defensive pressures applied team2,dif
0,QATAR,ECUADOR,42,50,8%,0,2,20 NOV 2022,17 : 00,Group A,...,1,6,5,0,0,52,72,256,279,8
1,ENGLAND,IRAN,72,19,9%,6,2,21 NOV 2022,14 : 00,Group B,...,1,8,13,0,0,63,72,139,416,53
2,SENEGAL,NETHERLANDS,44,45,11%,0,2,21 NOV 2022,17 : 00,Group A,...,0,9,15,0,0,63,73,263,251,1
3,UNITED STATES,WALES,51,39,10%,1,1,21 NOV 2022,20 : 00,Group B,...,1,7,7,0,0,81,72,242,292,12
4,ARGENTINA,SAUDI ARABIA,64,24,12%,1,2,22 NOV 2022,11 : 00,Group C,...,0,4,14,0,0,65,80,163,361,40

In [9]:
data["team1_eff"] = data["number of goals team1"] / data["possession team1"]
data["team2_eff"] =  data["number of goals team2"] / data["possession team2"]
data.head()
max_eff = 0
most_eff_team = "" 
for team in data["team1"].unique():
    eff = (data[data["team1"] == team]["team1_eff"].mean() + 
                    data[data["team2"] == team]["team2_eff"].mean()) / 2
    if eff > max_eff:
        max_eff = eff
        most_eff_team = team

In [10]:
print('----MOST EFFICIENT TEAM ----')
print(most_eff_team, 'efficiency:', max_eff)

----MOST EFFICIENT TEAM ----
JAPAN efficiency: 0.07402597402597402